function res = normalInvGamma( alpha, beta, delta, gammaVar, sigma, mu )
% TODO fill out this function
P = sqrt(gammaVar)*(beta^alpha)...
    /((sigma*sqrt(2*pi))*gamma(alpha))...
    *(1/(sigma^2))^(alpha+1)...
    *exp( -  (2*beta+gammaVar*((delta-mu))^2) / (2*sigma^2)   );
res = P;
        
